# Przykład 1

0,1.0,1.3,0.6 <br/>
1,2.0,2.1,0.7 <br/>
2,3.0,4.8,0.8 <br/>
3,4.0,3.3,0.9 <br/>

In [25]:
import numpy as np
import pandas as pd
x = np.array([[1, 1.3, 0.6], [2, 2.1, 0.7], [3, 4.8, 0.8],[4, 3.3, 0.9]])
df = pd.DataFrame(x)
outfile = 'data.txt'
df.to_csv(outfile,header=False)

In [26]:
data = np.loadtxt('data.txt', delimiter=',')
print(data)

[[ 0.   1.   1.3  0.6]
 [ 1.   2.   2.1  0.7]
 [ 2.   3.   4.8  0.8]
 [ 3.   4.   3.3  0.9]]


In [27]:
df = pd.read_csv('data.txt', header=None)
df.head()

0    1    2    3
0  0  1.0  1.3  0.6
1  1  2.0  2.1  0.7
2  2  3.0  4.8  0.8
3  3  4.0  3.3  0.9

In [28]:
df.values

array([[ 0. ,  1. ,  1.3,  0.6],
       [ 1. ,  2. ,  2.1,  0.7],
       [ 2. ,  3. ,  4.8,  0.8],
       [ 3. ,  4. ,  3.3,  0.9]])

In [29]:
df = pd.read_csv('data.txt')
df

0  1.0  1.3  0.6
0  1  2.0  2.1  0.7
1  2  3.0  4.8  0.8
2  3  4.0  3.3  0.9

In [30]:
df.values

array([[ 1. ,  2. ,  2.1,  0.7],
       [ 2. ,  3. ,  4.8,  0.8],
       [ 3. ,  4. ,  3.3,  0.9]])

# Przykład 2

ID,Weight,Value <br/>
1.0,1.3,0.6 <br/>
2.0,2.1,0.7 <br/>
3.0,4.8,0.8 <br/>
4.0,3.3,0.9 <br/>

In [31]:
x = np.array([[1, 1.3, 0.6], [2, 2.1, 0.7], [3, 4.8, 0.8],[4, 3.3, 0.9]])
df = pd.DataFrame(x, columns=['ID', 'Weight', 'Value'] )
outfile = 'data2.txt'
df.to_csv(outfile,index=False)

In [32]:
data = np.loadtxt('data2.txt', delimiter=',')
data

ValueError: could not convert string to float: b'ID'

In [33]:
df = pd.read_csv('data2.txt', header=None)
df

0       1      2
0   ID  Weight  Value
1  1.0     1.3    0.6
2  2.0     2.1    0.7
3  3.0     4.8    0.8
4  4.0     3.3    0.9

In [34]:
df.values

array([['ID', 'Weight', 'Value'],
       ['1.0', '1.3', '0.6'],
       ['2.0', '2.1', '0.7'],
       ['3.0', '4.8', '0.8'],
       ['4.0', '3.3', '0.9']], dtype=object)

In [35]:
df = pd.read_csv('data2.txt')
df

ID  Weight  Value
0  1.0     1.3    0.6
1  2.0     2.1    0.7
2  3.0     4.8    0.8
3  4.0     3.3    0.9

In [36]:
df.values

array([[ 1. ,  1.3,  0.6],
       [ 2. ,  2.1,  0.7],
       [ 3. ,  4.8,  0.8],
       [ 4. ,  3.3,  0.9]])

# Przykład 3

ID, Weight, Value <br />
1, 1.3, 0.6 <br />
2, 2.1, 0.7 <br />
3, 4.8, 0.8 <br />
4, 3.3, 0.9 <br />
<br />
blad<br />
Ja, 2017 <br />

In [37]:
x = np.array([[1, 1.3, 0.6], [2, 2.1, 0.7], [3, 4.8, 0.8],[4, 3.3, 0.9]])
df = pd.DataFrame(x, columns=['ID', 'Weight', 'Value'] )
outfile = 'data3.txt'
df.to_csv(outfile,index=False)

f = open('data3.txt', 'a')
f.write('\n')
f.write('blad\n')
f.write('Ja, 2017')
f.close() 

In [38]:
df = pd.read_csv('data3.txt',engine='python',skipfooter=3, delimiter='[ ,]*')
df

D:\Anaconda3\lib\site-packages\pandas\io\parsers.py:1961: FutureWarning: split() requires a non-empty pattern match.
  yield pat.split(line.strip())
D:\Anaconda3\lib\site-packages\pandas\io\parsers.py:1963: FutureWarning: split() requires a non-empty pattern match.
  yield pat.split(line.strip())


ID  Weight  Value
0  1.0     1.3    0.6
1  2.0     2.1    0.7
2  3.0     4.8    0.8
3  4.0     3.3    0.9

In [39]:
df.values

array([[ 1. ,  1.3,  0.6],
       [ 2. ,  2.1,  0.7],
       [ 3. ,  4.8,  0.8],
       [ 4. ,  3.3,  0.9]])

In [40]:
df.Value

0    0.6
1    0.7
2    0.8
3    0.9
Name: Value, dtype: float64

In [41]:
df["Value"]

0    0.6
1    0.7
2    0.8
3    0.9
Name: Value, dtype: float64